name: hl2ss-env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - numpy
  - portaudio
  - open3d
  - pytorch
  - torchvision
  - pip
  - pip:
      - opencv-python
      - av
      # Optional packages
      - pynput
      - PyAudio

