
name: hl2ss
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python==3.8
  - numpy
  - portaudio
  - pytorch
  - torchvision
  - pip
  - pip:
      - opencv-python
      - open3d==0.13.0
      # Optional packages
      - pynput
      - PyAudio